TicketMidia/Models/TB_FILME.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FILME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_FILME()
        {
            this.TB_PROGRAMA = new HashSet<TB_PROGRAMA>();
            this.TB_SESSAO_ANCINE = new HashSet<TB_SESSAO_ANCINE>();
        }
    
        public string FIL_CD_ANCINE { get; set; }
        public long DIS_CNPJ { get; set; }
        public string FIL_NM { get; set; }
        public string FIL_ID_NACIO { get; set; }
        public string FIL_DIGITAL { get; set; }
        public string FIL_GENERO { get; set; }
        public Nullable<int> FIL_CLASS_ETA { get; set; }
        public string FIL_DIRETOR { get; set; }
        public string FIL_SINOPSE { get; set; }
        public Nullable<System.DateTime> FIL_DT_INICIO { get; set; }
        public Nullable<System.DateTime> FIL_DT_FIM { get; set; }
        public Nullable<System.DateTime> FIL_ANO_LANC { get; set; }
        public string FIL_PAIS { get; set; }
        public string FIL_CD_AUX { get; set; }
        public Nullable<System.DateTime> FIL_DT_INC { get; set; }
        public Nullable<System.DateTime> FIL_DT_ALT { get; set; }
        public Nullable<System.DateTime> FIL_DT_DES { get; set; }
        public string FIL_MOT_DES { get; set; }
    
        public virtual TB_DISTRIBUIDORA TB_DISTRIBUIDORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROGRAMA> TB_PROGRAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SESSAO_ANCINE> TB_SESSAO_ANCINE { get; set; }
    }
}

TicketMidia/Controllers/TB_FILMEController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TicketMidia.Models;
using PagedList;


namespace TicketMidia.Controllers
{
    public class TB_FILMEController : Controller
    {
        private TicketMidiaEntities db = new TicketMidiaEntities();

        // GET: TB_FILME
        public ActionResult Index(string sortOrder ,string currentFilter ,string searchString ,int? page ,DateTime? CurrentDtSearch ,DateTime? DtSearch)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.InclusaoSortParm = sortOrder == "inclusao" ? "inclusao_desc" : "inclusao";
            ViewBag.FilmeSortParm = string.IsNullOrEmpty(sortOrder) ? "filme" : "";
            ViewBag.DistrSortParm = string.IsNullOrEmpty(sortOrder) ? "distr" : "";
            ViewBag.NacSortParm = string.IsNullOrEmpty(sortOrder) ? "nac" : "";

            if (searchString == null)
            {
                searchString = currentFilter;
            }

            if (!DtSearch.HasValue)
            {
                DtSearch = CurrentDtSearch;
            }

            //Atualiza a busca atual para a próxima página (se houver)
            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentDtSearch = DtSearch;

            var listaFilme = from s in db.TB_FILME
                             where s.FIL_DT_DES == null
                             select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                listaFilme = listaFilme.Where(s => s.FIL_NM.ToUpper().Contains(searchString.ToUpper()) || s.TB_DISTRIBUIDORA.DIS_NM.ToUpper().Contains(searchString.ToUpper()) || s.FIL_ID_NACIO.ToUpper().Contains(searchString.ToUpper())).Include(t => t.TB_DISTRIBUIDORA).OrderBy(t => t.FIL_NM);
            }

            if (DtSearch.HasValue)
            {
                listaFilme = listaFilme.Where(s => s.FIL_DT_INC >= DtSearch).Include(t => t.TB_DISTRIBUIDORA).OrderBy(t => t.FIL_NM);
            }

            switch (sortOrder)
            {
                case "inclusao":
                listaFilme = listaFilme.OrderBy(s => s.FIL_DT_INC);
                break;
                case "inclusao_desc":
                listaFilme = listaFilme.OrderByDescending(s => s.FIL_DT_INC);
                break;
                case "distr":
                listaFilme = listaFilme.OrderBy(s => s.TB_DISTRIBUIDORA.DIS_NM);
                break;
                case "nac":
                listaFilme = listaFilme.OrderBy(s => s.FIL_ID_NACIO);
                break;
                case "filme":
                listaFilme = listaFilme.OrderBy(s => s.FIL_NM);
                break;
                default:
                listaFilme = listaFilme.OrderBy(s => s.FIL_NM);
                break;
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(listaFilme.ToPagedList(pageNumber ,pageSize));

        }

        // GET: TB_FILME/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_FILME tB_FILME = db.TB_FILME.Find(id);
            if (tB_FILME == null)
            {
                return HttpNotFound();
            }
            return View(tB_FILME);
        }

        // GET: TB_FILME/Create
        public ActionResult Create()
        {
            ViewBag.DIS_CNPJ = new SelectList(db.TB_DISTRIBUIDORA.OrderBy(t => t.DIS_NM) ,"DIS_CNPJ" ,"DIS_NM");
            return View();
        }

        // POST: TB_FILME/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            string inlineRadioOptions = "";
            string FIL_COD_GEN = "";
            Random rdmCodGen = new Random();
            int iCodGen=0;
            string strAux="";
            int itamanho = 0;

            TB_FILME TB_FIL = new TB_FILME();
            
            foreach (var key in collection.AllKeys)
            {
                var value = collection[key];

                if (key == "FIL_CD_ANCINE") { TB_FIL.FIL_CD_ANCINE = value; }
                if (key == "FIL_COD_GEN") { FIL_COD_GEN = value; }
                if (key == "inlineRadioOptions") { inlineRadioOptions = value; }
                if (key == "DIS_CNPJ") { TB_FIL.DIS_CNPJ = Convert.ToInt64(value); }
                if (key == "FIL_NM") { TB_FIL.FIL_NM = value; }
                if (key == "FIL_ID_NACIO") { TB_FIL.FIL_ID_NACIO = value; }
                if (key == "FIL_DT_INC") { TB_FIL.FIL_DT_INC = Convert.ToDateTime(value); }
            }

            if (inlineRadioOptions == "2")
            {
                iCodGen = rdmCodGen.Next();
                strAux = iCodGen.ToString();
                itamanho = strAux.Length;

                if(itamanho > 11)
                {
                    itamanho = 11;
                }

                TB_FIL.FIL_CD_ANCINE = FIL_COD_GEN + "|" + strAux.Substring(0 ,itamanho);
            }


            db.TB_FILME.Add(TB_FIL);
            db.SaveChanges();

            return RedirectToAction("Index");


            //if (ModelState.IsValid)
            //{
            //    db.TB_FILME.Add(tB_FILME);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //ViewBag.DIS_CNPJ = new SelectList(db.TB_DISTRIBUIDORA, "DIS_CNPJ", "DIS_NM", tB_FILME.DIS_CNPJ);
            //return View(tB_FILME);
        }

        // GET: TB_FILME/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_FILME tB_FILME = db.TB_FILME.Find(id);
            if (tB_FILME == null)
            {
                return HttpNotFound();
            }
            ViewBag.DIS_CNPJ = new SelectList(db.TB_DISTRIBUIDORA, "DIS_CNPJ", "DIS_NM", tB_FILME.DIS_CNPJ);
            return View(tB_FILME);
        }

        // POST: TB_FILME/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FIL_CD_ANCINE,DIS_CNPJ,FIL_NM,FIL_ID_NACIO,FIL_DIGITAL,FIL_GENERO,FIL_CLASS_ETA,FIL_DIRETOR,FIL_SINOPSE,FIL_DT_INICIO,FIL_DT_FIM,FIL_ANO_LANC,FIL_PAIS,FIL_CD_AUX,FIL_DT_INC,FIL_DT_ALT,FIL_DT_DES,FIL_MOT_DES")] TB_FILME tB_FILME)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tB_FILME).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DIS_CNPJ = new SelectList(db.TB_DISTRIBUIDORA, "DIS_CNPJ", "DIS_NM", tB_FILME.DIS_CNPJ);
            return View(tB_FILME);
        }

        // GET: TB_FILME/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_FILME tB_FILME = db.TB_FILME.Find(id);
            if (tB_FILME == null)
            {
                return HttpNotFound();
            }
            return View(tB_FILME);
        }

        // POST: TB_FILME/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TB_FILME tB_FILME = db.TB_FILME.Find(id);
            db.TB_FILME.Remove(tB_FILME);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TicketMidia/Views/TB_FILME/Create.cshtml
@model TicketMidia.Models.TB_FILME

@{
    ViewBag.Title = "Create";
}

<h2>Novo Filme</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <br />
        @Html.ValidationSummary(true ,"" ,new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Código Ancine</label>
            <label class="radio-inline">
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="1" checked> ROE / CPB
                @Html.EditorFor(model => model.FIL_CD_ANCINE ,new { htmlAttributes = new { @class = "form-control input-sm" ,maxlength = "14" } })
            </label>
            <label class="radio-inline">
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="2"> Código Genérico
                <select name="FIL_COD_GEN" class="form-control input-sm" id="FIL_COD_GEN" style="text-align:center">
                    <option value="G4">Mostras e Festivais</option>
                    <option value="G2">Shows e Musicais</option>
                    <option value="G1">Eventos Esportivos</option>
                    <option value="G3">Jogos Eletrônicos</option>
                </select>
            </label>
        </div>
        <hr />
        <div class="form-group">
            <label class="control-label col-md-2">Distribuidora</label>
            <div class="col-md-10">
                @Html.DropDownList("DIS_CNPJ" ,null ,htmlAttributes: new { @class = "form-control input-sm" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nome do Filme</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.FIL_NM ,new { htmlAttributes = new { @class = "form-control input-sm", maxlength = "50" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nacionalidade</label>
            <div class="col-md-4">
                <select name="FIL_ID_NACIO" class="form-control input-sm" id="FIL_ID_NACIO">
                    <option value="E">Estrangeiro</option>
                    <option value="N">Nacional</option>
                </select>
                @Html.ValidationMessageFor(model => model.FIL_ID_NACIO ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_DIGITAL ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_DIGITAL ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_DIGITAL ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_GENERO ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_GENERO ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_GENERO ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_CLASS_ETA ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_CLASS_ETA ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_CLASS_ETA ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_DIRETOR ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_DIRETOR ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_DIRETOR ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_SINOPSE ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_SINOPSE ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_SINOPSE ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_DT_INICIO ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_DT_INICIO ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_DT_INICIO ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_DT_FIM ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_DT_FIM ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_DT_FIM ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_ANO_LANC ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_ANO_LANC ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_ANO_LANC ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_PAIS ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_PAIS ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_PAIS ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_CD_AUX ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_CD_AUX ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_CD_AUX ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_DT_INC ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_DT_INC ,new { htmlAttributes = new { @Value = DateTime.Now.ToString("dd/MM/yyyy hh:mm:ss") } })
                @Html.ValidationMessageFor(model => model.FIL_DT_INC ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_DT_ALT ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_DT_ALT ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_DT_ALT ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_DT_DES ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_DT_DES ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_DT_DES ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.FIL_MOT_DES ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.FIL_MOT_DES ,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIL_MOT_DES ,"" ,new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="text-align:right">
                <a href="/TB_FILME" class="btn btn-default btn-md" role="button">Voltar</a>
                <input type="submit" value="Salvar" class="btn btn-success btn-md" id="btnSalvar" name="btnSalvar"/>
            </div>
        </div>
    </div>

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        $(document).ready(function () {

            $('#btnSalvar').click(function ()
            {
                var element2 = document.getElementById('inlineRadio1');
                if (element2.checked == true) {
                    var element3 = document.getElementById('FIL_CD_ANCINE');
                    if (element3.value == "") {
                        alert("Informar o ROE ou CPB da Obra");
                        return false;
                    }
                }

                var element3 = document.getElementById('FIL_CD_ANCINE');
                if (element3.length < 14) {
                    alert("O ROE ou CPB da Obra deve possuir 14 caracteres.");
                    return false;
                }

                var element = document.getElementById('FIL_NM');
                if (element.value == "") {
                    alert("Informar o nome da Obra (Filme)");
                    return false;
                }
            })

            $('#btnTeste').click(function () 
            {
                var element4 = document.getElementById('FIL_CD_ANCINE');
                element4.alert.length;
            })
        });
    </script>

}

TicketMidia/Views/TB_FILME/Index.cshtml
@model PagedList.IPagedList<TicketMidia.Models.TB_FILME>
@using PagedList.Mvc;
@using TicketMidia.Helpers;

@{
    ViewBag.Title = "Index";
    
}

<h3>Filmes</h3>


@using (Html.BeginForm("Index" ,"TB_FILME" ,FormMethod.Post ,htmlAttributes: new { id = "frmPesq" }))
{
    <table class="table">
        <tr>

            <th style="text-align:right">
                @Html.TextBox("DtSearch" ,ViewBag.CurrentDtSearch as string ,htmlAttributes: new { @class = "input-xs" ,style = "text-align:center" ,placeholder = "Data Inclusão" ,autocomplete = "off" })&nbsp; ou &nbsp;
                @Html.TextBox("SearchString" ,ViewBag.CurrentFilter as string ,htmlAttributes: new { @class = "input-xs" ,placeholder = "Filme, Distribuidora..." ,autocomplete = "off" })&nbsp;
                <a href="#" class="btn btn-info btn-sm" onclick="$('#frmPesq').submit();">Pesquisar</a>
                &nbsp;<a href="/TB_FILME" class="btn btn-default btn-sm">Limpar Pesquisa</a>
            </th>
            <th style="text-align:right">
                <a href="/TB_FILME/Create" class="btn btn-success btn-sm">Novo Filme</a>
            </th>
        </tr>
    </table>
}


<table class="table small table-striped table-hover">
    <tr class="info">
        <th>
            Código Ancine
        </th>
        <th>
            <u>@Html.ActionLink("Filme" ,"Index" ,new { sortOrder = ViewBag.FilmeSortParm ,currentFilter = ViewBag.CurrentFilter })</u>
        </th>
        <th>
            <u>@Html.ActionLink("Distribuidora" ,"Index" ,new { sortOrder = ViewBag.DistrSortParm ,currentFilter = ViewBag.CurrentFilter })</u>
        </th>
        <th>
            <u>@Html.ActionLink("Nac / Est" ,"Index" ,new { sortOrder = ViewBag.NacSortParm ,currentFilter = ViewBag.CurrentFilter })</u>
        </th>
        <th style="text-align:center">
            <u>@Html.ActionLink("Inclusão" ,"Index" ,new { sortOrder = ViewBag.InclusaoSortParm ,currentFilter = ViewBag.CurrentFilter })</u>
        </th>
        <th style="text-align:center">
            Alteração
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    var clsHelper = new Helpers();
                    var codAncine = item.FIL_CD_ANCINE;
                    var strCodAncine = "";
                    if(codAncine != "")
                    {
                        strCodAncine = clsHelper.FormataCodigoObraGenerica(codAncine);

                        if (strCodAncine != "")
                        {
                            codAncine = strCodAncine;
                        }

                    }
                }
                <div>@codAncine</div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FIL_NM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TB_DISTRIBUIDORA.DIS_NM)
            </td>
            <td>
                @{
                    var nac = item.FIL_ID_NACIO;
                    if (nac == "E")
                    { nac = "Estrangeiro"; }
                    else
                    { nac = "Nacional"; }
                }
                <div>@nac</div>
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.FIL_DT_INC)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.FIL_DT_ALT)
            </td>
            <td style="text-align:center">
                <a href="/TB_FILME/Edit/@item.FIL_CD_ANCINE" class="btn btn-info btn-xs">Editar</a>
                <a href="/TB_FILME/Delete/@item.FIL_CD_ANCINE" class="btn btn-danger btn-xs">Excluir</a>
            </td>
        </tr>
                    }

</table>

Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
@Html.PagedListPager(Model ,page => Url.Action("Index" ,new { page ,sortOrder = ViewBag.CurrentSort ,currentFilter = ViewBag.CurrentFilter }))

@section Scripts
{
    <script type="text/javascript">

        function ClearObj() {

            //alert("ok");
            var element = document.getElementById("SearchString");
            element.value = "";

            var element2 = document.getElementById("DtSearch");
            element2.value = "";

        };

        window.onload = ClearObj;

        function fnExcelReport() {
            var tab_text = "<table border='2px'><tr bgcolor='#87AFC6'>";
            var textRange; var j = 0;
            tab = document.getElementById('prog_index'); // id of table

            for (j = 0 ; j < tab.rows.length ; j++) {
                tab_text = tab_text + tab.rows[j].innerHTML + "</tr>";
                //tab_text=tab_text+"</tr>";
            }

            tab_text = tab_text + "</table>";
            tab_text = tab_text.replace(/<A[^>]*>|<\/A>/g, "");//remove if u want links in your table
            tab_text = tab_text.replace(/<img[^>]*>/gi, ""); // remove if u want images in your table
            tab_text = tab_text.replace(/<input[^>]*>|<\/input>/gi, ""); // reomves input params

            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");

            if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./))      // If Internet Explorer
            {
                txtArea1.document.open("txt/html", "replace");
                txtArea1.document.write(tab_text);
                txtArea1.document.close();
                txtArea1.focus();
                sa = txtArea1.document.execCommand("SaveAs", true, "Say Thanks to Sumit.xls");
            }
            else                 //other browser not tested on IE 11
            {
                sa = window.open('data:application/vnd.ms-excel,' + encodeURIComponent(tab_text));
            }
            return (sa);
        }


        $(function () {
            $(document).ready(function () {
                $('#DtSearch').datepicker({
                    dateFormat: "dd/mm/yy",
                    showStatus: true,
                    showWeek: true,
                    showOtherMonths: false,
                    selectOtherMonths: true,
                    autoSize: true,
                    gotoCurrent: true,
                    highlightWeek: true,
                });
            });

        });
    </script>
}